# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The '2' in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

# -*- set/update these before vagrant up the vm -*-
VGT_BOX = 'ubuntu/trusty64'
APP_BASE_PATH = 'devworks/apptest' # eg: '[cpny]works/app'
APP_NAME = APP_BASE_PATH.split('/').last

Vagrant.configure(2) do |config|
  config.vm.box = VGT_BOX

  # Sync'd folders
  config.vm.synced_folder '.',         '/vagrant',  disabled: true
  
  # app working directory is '..' (itself) and it's shared between Host and Guest OS.
  config.vm.synced_folder '..',        "/home/#{ APP_BASE_PATH }", create: true

  # This will save deb files under your [app_working_dir]/.vgt/apt-archives,
  # so that you won't need to download them again when re-building environment
  # This will save you time and money (if you pay for traffic)
  config.vm.synced_folder './apt-archives', '/var/cache/apt/archives/', create: true

  # Ubuntu VM
  config.vm.define "#{ APP_NAME }.dev" do |ub|
    ub.vm.hostname = "#{ APP_NAME }.dev"
    ub.vm.network 'private_network', ip: '10.20.30.100'
    ub.vm.network :forwarded_port, guest: 3000, host: 3000
    ub.vm.provision 'shell', path: './provision/bootstrap.sh', privileged: false
  end
end
